
clear
clc
close all

Dias = [2:1:5];
% Dias = 3;
family  = 'NACA';
fpath = 'C:\users\sdivi\Documents\AUV\NREL Codes\HARP_Opt - old\Output_Files\';
attachments = 'v2';

cd('C:\users\sdivi\Documents\AUV\NREL Codes\Code Checks\');

[RotDesMat,RotPerfMat] = ReadTurbDesFiles(fpath,family,Dias,attachments);



for i = 1:length(RotPerfMat)
    radpersec = RotPerfMat{i}(:,2).*0.1047; % rads per sec
    TSR = ((0.5*Dias(i)).*radpersec)./RotPerfMat{i}(:,1);
    [r,c] = size(RotPerfMat{i});
    c = c + 1;
    temp = zeros(r,c);
    for k = 1:size(temp,2)
        if k < 3
            temp(:,k) = RotPerfMat{i}(:,k);
        elseif k == 3
            temp(:,k) = TSR;
        else
            temp(:,k) = RotPerfMat{i}(:,k-1);
        end
    end
            
    RotPerfMat{i} = temp;
end

% Performance Mapping after incorporating a duct
for i = 1:length(RotPerfMat)
    
    rho = 1025;

    Cpduct_des = 0.5;
    Beta = 1.47;
    vrated = 2;

    Prated = 0.001*Cpduct_des*0.5*rho*Beta*0.25*pi*Dias(i)^2*vrated^3;

    A = (RotPerfMat{i}(:,1) > vrated); ind = []; zind = [];
    for k = 1:length(A)
        if A(k)> 0 
            ind = vertcat(ind,k);
        else
            zind = vertcat(zind,k);
        end
    end

    Cpduct2 = zeros(length(A),1);

    for k = 1:length(ind)
        vtemp(k) = RotPerfMat{i}(ind(k),1);
    end
%     vtemp = vtemp';

    Cpduct1 = Cpduct_des.*(ones(length(zind),1));
    Cpduct2 = Prated./((0.001*Beta*0.5*rho*0.25*pi*Dias(i)^2).*(vtemp.^3));
    Cpduct{i} = vertcat(Cpduct1,Cpduct2');
    Pducted{i} = 0.001*Cpduct{i}*0.5*rho*Beta*0.25*pi*(Dias(i).^2).*(RotPerfMat{i}(:,1).^3); % kW
    Cqduct{i} = (0.5*Dias(i)*Cpduct{i})./RotPerfMat{i}(:,3); % normalized wrt diffuser exit area
    Tauduct{i} = 0.001*Cqduct{i}*0.5*rho*Beta*0.25*pi*Dias(i)^2.*(RotPerfMat{i}(:,1).^2); % kN-m
    
end

% Dt = [0.5:0.5:5];
Dt = 3;
for i = 1:length(Dt)   
    vel = RotPerfMat{1}(:,1);
    Pow{i} = 0.001*Cpduct{1}*0.5*rho*Beta*0.25*pi*(Dt(i).^2).*(vel.^3);
    AUVPow{i} = 0.9*0.95*2.*Pow{i}; 

end

clrs = [0 0 0;0 0 1;0 1 0;0 1 1;1 0 0;1 0 1;1 0.5 0.5;1 0.5 0;0.5 0.5 0.5;0.5 0.5 1];

figure(1)
for i = 1:length(AUVPow)
    plot(vel,AUVPow{i},'Color',clrs(i,:),'LineWidth',1.75);
    hold on
    leg(i) = cellstr(['Turbine Dia = ',num2str(Dt(i))]);
end

xlabel('GS Speeds (m/s)')
ylabel('Power (kW)')
title('Power Generated by the AUV')
grid on
legend(leg,'Location','northwest')
set(gca, 'FontName', 'Calibri');
set(gca, 'FontSize', 18);   
set(gcf, 'Color', [1, 1, 1])
% fpath = 'C:\Users\sdivi\Documents\AUV\Thesis\Pictures\';
% filename = ['Case3FA_PowerCurve_vrated',num2str(vrated)];
% saveas(gcf,fullfile(fpath,filename),'jpeg');
fpath = 'C:\Users\sdivi\Documents\AUV\Thesis\Pictures\';
filename = ['Prototype_PowerCurve_vrated',num2str(vrated)];
saveas(gcf,fullfile(fpath,filename),'jpeg');



